export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const UPDATE_CART = 'UPDATE_CART';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const PASSWORD_UPDATE_SUCCESS = 'PASSWORD_UPDATE_SUCCESS';
export const PASSWORD_UPDATE_FAIL = 'PASSWORD_UPDATE_FAIL';
export const PASSWORD_FORGOT_SUCCESS = 'PASSWORD_FORGOT_SUCCESS';
export const PASSWORD_FORGOT_FAIL = 'PASSWORD_FORGOT_FAIL';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const CLEAR_SUCCESS = 'CLEAR_SUCCESS';

export const START_LOADING = 'START_LOADING';

export const UPDATE_DELIVERY = 'UPDATE_DELIVERY';

export const GET_ALL_ORDERS = 'GET_ALL_ORDERS';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const DELETE_ORDER = 'DELETE_ORDER';
export const ORDER_UPDATE_FAIL = 'ORDER_UPDATE_FAIL';
export const ORDER_DELETE_FAIL = 'ORDER_DELETE_FAIL';

export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const CATEGORY_ERROR = 'CATEGORY_ERROR';
export const SET_NEW_CATEGORY = 'SET_NEW_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const CATEGORY_UPDATE_FAIL = 'CATEGORY_UPDATE_FAIL';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const CATEGORY_DELETE_FAIL = 'CATEGORY_DELETE_FAIL';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const CATEGORY_CREATE_FAIL = 'CATEGORY_CREATE_FAIL';

export const GET_ORDERS = 'GET_ORDERS';
export const ADD_ORDER = 'ADD_ORDER';
export const CLEAR_ORDERS = 'CLEAR_ORDERS';
export const ORDER_ERROR = 'ORDER_ERROR';

export const UPDATE_NEW = 'UPDATE_NEW';
export const UPDATE_CURRENT = 'UPDATE_CURRENT';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const CLEAR_BOTH = 'CLEAR_BOTH';
